Seven tutorials to be part of the storynavigator documentation, section 'tutorials'
navigating-stories/orange-story-navigator pull request #117
Opened 2024-10-07 15:56 UTC by ThijsVroegh

Continuing on the workflows demonstration in the last workshop (see attached presentation here [18092024_navigatingstories.pptx](https://github.com/user-attachments/files/17281236/18092024_navigatingstories.pptx)), I wrote several tutorials on how to use the storynavigator widgets in more advanced pipelines and answering research questions from the domain of narrative structure. These tutorials will be part of the documentation (https://orange-story-navigator.readthedocs.io/en/latest/).

2024-10-08 16:04 UTC, eriktks requested changes
These new tutorials will be very helpful for users of the Story Navigator to become familiar with the applications made possible by the software. Thanks for developing these! Here are comments per tutorial:

**1. Agency**

1. Elements (1) is fed text without stop words which makes it more difficult to process the text. Elements (1) should be connected to Corpus (2) instead of to Preprocess Text
2. Try to avoid widget names like Widget (number). The numbers are necessary when there is more than one widget with the same name but not when there is only one widget with that name. To realize: remove all widgets with the same name and then replace all of them with new widgets
3. Do not use data viewing widgets in the main branch pipeline but use a separate branch, like for Word Cloud. So Select Rows (1) should be connected to Actors (1), Group by (1) should be connected to Select Rows (1), etc.
4. In Step 4 is missing instructions to connect the Elements with the Actors widget
5.  In Step 5 are missing the exact conditions for selecting the rows
6. Spelling befroe - before

**2. Sentiment**

1. see comment Agency 1.2 (Bar Plot (1))
2. see comment Agency 1.3 (Data Table)
3. the Corpus Viewer mentioned in Step 1 is not shown in the image
4. Note in the averages computed here, longer sentences have more weight since the averages are based on word scores
5. Step 7: can you select rows with the Data Table widget or do you need to use the Select Rows widget?

**3. Story radar plot**

1. see comment Agency 1.2 (Data Table (1) (2) and others)
2. see comment Agency 1.3 (Data Table (1) (2) and others)
3. Step 1: the Corpus widget cannot be used for inspecting the data, for this the Corpus Viewer is needed
4. Step 2: the File widget is not connected to a Data widget in the image
5. Step 6: the Halliday categories is not available to the Group by widget and cannot be used for grouping data
6. Step 7: the Halliday categories is not available to the Select rows widget and cannot be used for selecting data
7. Step 8: is missing
8. Step 9: the Halliday categories is not available to the Edit domain widget and cannot be used for plotting data
9. image: TODO text can be removed (isn't this tutorial 4?)
10. (Python script has not been tested)

**4. Character radar plot**

1. see comment Agency 1.2 (Elements (2) and others)
2. see comment Agency 1.3 (Data Table (3) and others)
3. I cannot import letters.tb with the widget Import Documents. Is this the right widget? Does it import files here? Then why is this widget's input different than that of the Elements widget?
4. Step 5: what conditions are used for the merge?
5. (the final Python script was not tested)
6. Should this analysis not be applied to only 1 story?

**5. Story settings with Orange**

1. see comment Agency 1.3 (Data Table)
2. spelling: occurrences (no "a")
3. Extra Step 4 after Step 2 and before Step 3 is redundant
4. Step 6: mention that the chosen Aggregated values for label and text need to be Concatenate
5. Conclusion: refers to tutorial 6 for settings with ChatGPT but actually that is tutorial 7

**6. Verb tense**

1. see comment Agency 1.2 (Select Columns (1))
2. see comment Agency 1.3 (Data Table (1) and others)
3. more later...


**7. Story settings with ChatGPT**

1. Step 2: mention that the user needs a ChatGTP key to run this tutorial
2. In Step 2 the first prompt "Make an anlysis..." is redundant and can be removed
4. Step 4: explain how to get the colors shown in the image: by specifying N under Selection?
5. Step 5: explain how to make ChatGPT analyze a single cluster: by clicking on the cluster in Hierarchical Clustering?

2024-12-16 15:29 UTC, ThijsVroegh commented
Hi @eriktks thanks again for the comments on the tutorials. I updated all 7 tutorials, except for the following aspect:

tutorial 6:
**to get the percentage of present verbs per story: use Continuize widget after Merge Data widget and there select "First value as base" for column story_navigator_tag; then Select Columns story_navigator_tag=PRES_VB and story_id; and then Group By story_id while computing mean for column story_navigator_tag=PRES_VB**

I did not manage to get this working. Just let me know if you agree with the updates, then I'll merge then in master

2025-01-16 17:13 UTC, eriktks requested changes
Thanks for attending to the comments of the previous review! I have checked the current state of the tutorials and I have a few more questions and requests for changes. Most of these can be attended by accepting the change proposals. Some of these require more time. Perhaps we can look at these together.

2025-01-16 17:13 UTC, eriktks commented on doc/widgets/tutorial7.md
> +Deploy the **ChatGPT Summarize** widget to generate summaries for each cluster, providing insights into shared themes or settings.
I was unable to get any output out of ChatGPT. Perhaps I am hitting some rate limits. Was it intentional that ChatGPT was fed with stories and not with story setting summaries?

2025-01-21 11:07 UTC, merged