Restructure documentation and include missing information on installing the storynavigator widget
navigating-stories/orange-story-navigator pull request #69
Opened 2024-06-21 13:50 UTC by ThijsVroegh

##### Issue
- Some aspects were missing in the documentation, including how to install the widget as an add-on
- Restructure the documentation allong 
- Getting Started
- Widgets
- Known issues
- Contact information

##### Description of changes
changed widgets.json and index.rst to accomate missing pages

##### Includes
- [] Code changes
- [ ] Tests
- [ X] Documentation

2024-06-25 09:34 UTC, ThijsVroegh commented
@kodymoodley Hi Kody, can you take a look at the updated documentation and structure?

2024-06-25 11:02 UTC, kodymoodley commented on doc/widgets.json
> +    "text": "How to install the widget",
Installation

2024-06-25 11:05 UTC, kodymoodley commented on doc/widgets/contact.md
I guess this is copied and pasted text from "knownissues.md"? If so,  I would simply remove "contact.md" or leave it blank / put a "under construction..." notice (until we have content to put in this section). Otherwise, users might get confused when browsing the docs. Remember changes go live on rtd after committing / merging with master.

2024-06-25 11:06 UTC, kodymoodley commented on doc/widgets/contact.md
I mean you have "Known Issues" as the title. It should be "Contact" right?

2024-06-25 11:07 UTC, kodymoodley commented on doc/widgets/usage.md
> +How to enable StoryNavigator in Orange
You mean "Usage" right? Not "How to enable..."

2024-06-25 11:34 UTC, kodymoodley commented on doc/index.rst
> +   :caption: Contact Information
I thought about it a bit more. I would suggest the following structure:

- Getting Started
    - Installation
    - Usage
    - Tutorials
    - Known Issues
- Widgets
    - Actors
    - Actions
    - Setting
    - Narrative Network
- Developers
    - Building from source
    - Contribute
    - Changelog
- About
    - Contact
    - How to cite Story Navigator
    - In action
    - FAQs

"Usage" will show how to use each widget.
"Tutorials" will provide video tutorials with workflows that connect the widgets in order to answer some predefined research questions.
- Known issues: runtime issues that users might experience (with workarounds if available) and misconceptions about how SN works or what it is supposed to do
- "Building from source": contains instructions from Github on how to build SN from source
- "Contribute": contribution guidelines (styles / conventions we expect from contributors. E.g., "contact developers at developers@storynavigator.com first before submitting PRs. Use markdown for...etc.)
- "Changelog": list of featured added, removed / amended in each version
- "How to cite..": citiation.cff file for SN. bibtex entry (copy and paste box)
- "In action": links to projects, events, papers, blogposts, videos, etc. which mention or make use of SN.
- FAQs: frequently asked questions about SN with their answers. E.g., where can I find information about how to...?

2024-06-25 11:35 UTC, kodymoodley commented on doc/index.rst
> +   :caption: Contact Information
@ThijsVroegh @eriktks  what do you think?

2024-06-25 11:37 UTC, kodymoodley commented on doc/widgets/contact.md
>  Stay updated on the projecty by following us on:
typo: "projecty"

2024-06-25 11:38 UTC, kodymoodley commented on doc/widgets/contact.md
>  Stay updated on the projecty by following us on:
is this last line meant to link to something like Twitter? If so, remove it. They can use the contact info about rather.

2024-07-01 07:21 UTC, ThijsVroegh commented on doc/index.rst
> +   :caption: Contact Information
Thanks @kodymoodley. This looks like a well-defined structure! I updated the structure of the documentation page accordingly, and updated several of the pages already. I'll focus on two example workflows next as part of the 'tutorials' subpage

2024-07-01 07:27 UTC, ThijsVroegh commented
Thansk @kodymoodley for all suggestions! I included them and updated the structure of the page. Just let me know in case any other suggestions pop up

2024-07-02 12:46 UTC, kodymoodley requested changes
Thanks for your nice work @ThijsVroegh! The documentation is taking shape very nicely! :) Just some final things to add. If you only address these points and do not add other stuff, I am happy for you to merge directly to master after the changes (without requiring a further review from me).

2024-07-02 12:46 UTC, kodymoodley commented on doc/widgets/howtocite.md
> +authors:
Same here. Add missing developers' names, including Malte.

2024-07-02 12:46 UTC, kodymoodley commented on doc/widgets/inaction.md
> +"In action": links to projects, events, papers, blogposts, videos, etc. which mention or make use of SN.
Link to this blogpost: https://blog.esciencecenter.nl/the-orange3-data-mining-platform-as-a-research-tool-2167336a5c0d

2024-07-02 12:46 UTC, kodymoodley commented on doc/widgets/contribute.md
> +We have a [Code of Conduct](CODE_OF_CONDUCT.md), please follow it in all your interactions with the project.
Where is the "CODE OF CONDUCT.md" file?

2024-07-02 13:54 UTC, ThijsVroegh commented on doc/widgets/changelog.md
> +Change log
done

2024-07-02 13:56 UTC, ThijsVroegh commented on doc/widgets/inaction.md
> +"In action": links to projects, events, papers, blogposts, videos, etc. which mention or make use of SN.
done

2024-07-02 13:56 UTC, ThijsVroegh commented on doc/widgets/howtocite.md
> +authors:
done

2024-07-02 13:56 UTC, ThijsVroegh commented on doc/widgets/howtocite.md
> +  author = {Smeets, Stef and Vroegh, Thijs},
done

2024-07-02 13:56 UTC, ThijsVroegh commented on doc/widgets/installation.md
done

2024-07-02 13:57 UTC, ThijsVroegh commented on doc/widgets/contribute.md
> +We have a [Code of Conduct](CODE_OF_CONDUCT.md), please follow it in all your interactions with the project.
added

2024-07-02 14:11 UTC, merged