Add bump-my-version as a dependency
navigating-stories/orange-story-navigator pull request #80
Opened 2024-07-17 15:03 UTC by stefsmeets

Hi all, this PR sets up automatic version bumping as part of #67 

This uses [`bump-my-version`](https://github.com/callowayproject/bump-my-version), which bumps the version according to semver:

```
bump-my-version bump patch
# 0.0.20 -> 0.0.21
bump-my-version bump major
# 0.0.21 -> 0.1.0
bump-my-version bump major
# 0.1.0 -> 1.0.0
```

It bumps the version in all files in one go.

2024-08-13 11:49 UTC, stefsmeets commented
Gentle reminder, @ThijsVroegh 😅

2024-08-13 12:48 UTC, ThijsVroegh commented
@stefsmeets Thanks!! 👍 -)  It's on my list

2024-08-13 13:33 UTC, ThijsVroegh commented on pyproject.toml
> +current_version = "0.0.20"
Nevermind; I understand it from the code below..

2024-08-13 13:51 UTC, ThijsVroegh requested changes
These changes allow to automatically update the version number in different places in the package after the releaser sets the tag and version. After a new release, version bump, dependency pinning, and the upload to pypi all happen automatically. This solves issue #65.

I checked that there are indeed 3 places where the version is mentioned (excluding the init) 

Question:
- How is the order of first bumpen and then releasen accounted for (and not, for example, the other way around)? Or has this become irrelIevant?

2024-08-13 14:11 UTC, merged

2024-08-15 11:05 UTC, ThijsVroegh commented
Ok, thanks!